name: Build

on: [push]

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, windows-2019]
        include:
        - os: ubuntu-latest
          executable-file: DDNet-Server
        - os: windows-latest
          executable-file: DDNet-Server.exe
        - os: windows-2019
          executable-file: DDNet-Server.exe

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install cmake libsqlite3-dev -y

    - name: Build in release mode
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Release
        cmake --build ./ --config Release

    - name: Move release
      if: contains(matrix.os, 'windows')
      run: mv ./release/${{ matrix.executable-file }} ./

    - name: Test release
      run: ./${{ matrix.executable-file }} shutdown

    - name: Package
      run: |
        mkdir artifacts
        mv ${{ matrix.executable-file }} artifacts

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: huntern-${{ matrix.os }}
        path: artifacts